import { parsePaymentText, fxAmountOf, setFxRates } from "../src/lib/data.js";
import { autoRecordPayments } from "../src/lib/auto-record.js";
let fail = 0;
const check = (n, got, want) => { const ok = String(got) === String(want); if (!ok) fail++; console.log(`  ${ok ? "PASS" : "FAIL"}  ${n}${ok ? "" : `  (기대 ${want} / 실제 ${got})`}`); };
setFxRates({ USD: 1356, JPY: 8.62 });
console.log("[1] 외화 금액 읽기(해외승인 문자)");
const T = "[현대카드] 해외승인 홍*동님 10/01 03:15 USD 25.00 GoogleDigitalInc.";
const r = parsePaymentText(T);
check("원화 짐작 = 25 × 1356 × 1.012", r.amount, Math.round(25 * 1356 * 1.012));
check("가맹점 옆에 외화 표시", /GoogleDigitalInc\. \(USD 25 · 환율 짐작\)/.test(r.merchant), true);
check("엔화 3,000", fxAmountOf("해외승인 JPY 3,000 가맹점").krw, Math.round(3000 * 8.62 * 1.012));
check("'원'이 있으면 원화가 우선", parsePaymentText("승인 12,000원 USD 10 가맹점").amount, "12000");
check("통화 글자만 있고 숫자 없으면 안 읽음", fxAmountOf("USD 환율 안내"), null);
check("영단어 속 USD는 안 읽음(앞이 영문)", fxAmountOf("MUSD 25"), null);
console.log("\n[2] 자동 기록");
const d = { accounts: [{ id: "a1", name: "국민은행" }], cards: [{ id: "c1", name: "현대카드(코스트코)", bill: 0 }], categories: [], balanceEntries: [], fixedExpenses: [], expenses: [] };
const res = autoRecordPayments(d, [{ text: T, at: Date.now(), pkg: "com.samsung.android.messaging" }], []);
check("지출 1건", res.registered.length, 1);
check("카드값에 더함", res.next.cards[0].bill, Math.round(25 * 1356 * 1.012));
console.log(fail ? `\n${fail}건 실패` : "\n전부 통과"); process.exit(fail ? 1 : 0);
