import { autoRecordPayments } from "../src/lib/auto-record.js";
import { migrate } from "../src/lib/data.js";
let fail = 0;
const check = (n, got, want) => { const ok = String(got) === String(want); if (!ok) fail++; console.log(`  ${ok ? "PASS" : "FAIL"}  ${n}${ok ? "" : `  (기대 ${want} / 실제 ${got})`}`); };
const KB = "com.kbstar.kbbank";
const base = (incomes) => ({ accounts: [{ id: "a1", name: "국민은행", initialBalance: 1000000 }], cards: [], categories: [], expenses: [], balanceEntries: [], fixedExpenses: [], fixedIncomes: incomes });
const dep = (won, time = "10:05") => ({ text: `입금 ${won.toLocaleString("en-US")}원 홍*동님 09/25 ${time} 111111-**-***222 홍길동 입금 ${won.toLocaleString("en-US")} 잔액1,200,000`, pkg: KB, at: Date.now() });
console.log("[1] 같은 금액 입금 → 그 달 '들어옴'");
let r = autoRecordPayments(base([{ id: "i1", name: "가족 지원", amount: 200000, receivedMonths: {} }]), [dep(200000)], []);
check("들어옴 표시", !!r.next.fixedIncomes[0].receivedMonths["2026-09"], true);
check("입금 기록 메모", r.next.balanceEntries.find((b) => !b.isAdjustment)?.memo, "가족 지원 입금");
console.log("[2] 다른 금액은 그대로");
r = autoRecordPayments(base([{ id: "i1", name: "가족 지원", amount: 200000, receivedMonths: {} }]), [dep(150000)], []);
check("표시 안 함", Object.keys(r.next.fixedIncomes[0].receivedMonths).length, 0);
console.log("[3] 같은 금액 항목이 둘이면 어느 것인지 몰라 건드리지 않는다");
r = autoRecordPayments(base([{ id: "i1", name: "가", amount: 200000, receivedMonths: {} }, { id: "i2", name: "나", amount: 200000, receivedMonths: {} }]), [dep(200000)], []);
check("둘 다 그대로", r.next.fixedIncomes.every((i) => Object.keys(i.receivedMonths).length === 0), true);
console.log("[4] 이미 그 달 들어온 항목은 또 안 표시");
r = autoRecordPayments(base([{ id: "i1", name: "가족 지원", amount: 200000, receivedMonths: { "2026-09": "b0" } }]), [dep(200000)], []);
check("그대로 b0", r.next.fixedIncomes[0].receivedMonths["2026-09"], "b0");
console.log("[5] 손으로 먼저 적은 입금과 같은 알림이어도 표시");
const d5 = base([{ id: "i1", name: "가족 지원", amount: 200000, receivedMonths: {} }]);
d5.balanceEntries = [{ id: "b5", type: "in", amount: 200000, date: "2026-09-25", memo: "용돈", accountId: "a1" }];
r = autoRecordPayments(d5, [dep(200000)], []);
check("표시됨", !!r.next.fixedIncomes[0].receivedMonths["2026-09"], true);
console.log("[6] 옛 백업(고정 수입 없음)도 불러온다");
check("fixedIncomes 빈 목록", JSON.stringify(migrate({ accounts: [{ id: "a1", name: "통장" }] }).fixedIncomes), "[]");
check("있는 것은 보존", migrate({ fixedIncomes: [{ id: "i", name: "x", amount: 5 }] }).fixedIncomes[0].amount, 5);
check("깨진 항목은 버림", migrate({ fixedIncomes: [{ id: "i" }, null, { name: "y", amount: 0 }] }).fixedIncomes.length, 0);
console.log(fail ? `\n${fail}건 실패` : "\n전부 통과"); process.exit(fail ? 1 : 0);
